apiVersion: v1
kind: Secret
metadata:
  name: osss-secrets
type: Opaque
stringData:
  POSTGRES_PASSWORD: "osss"
  KEYCLOAK_DB_PASSWORD: "keycloak"
  KEYCLOAK_ADMIN: "a2a"
  KEYCLOAK_ADMIN_PASSWORD: "a2a"
