recipe: default.v1
language: en

# Simple, fast pipeline for a small starter bot
pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 40
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 40

policies:
- name: RulePolicy
- name: MemoizationPolicy
- name: TEDPolicy
  epochs: 40
assistant_id: 20251110-174339-median-time
